name: Node.js CI

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on
      - ci-test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Test
      run: pnpm test

    - name: Build
      run: pnpm build

    # - name: Get npm cache directory
    #   id: npm-cache-dir
    #   shell: bash
    #   run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    # - uses: actions/cache@v3.3.2
    #   id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
    #   with:
    #     path: ${{ steps.npm-cache-dir.outputs.dir }}
    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-

    # - name: Install dependencies
    #   run: npm ci

    # - name: Test
    #   run: npm run test

    # - name: Build
    #   run: npm run build